name: Fetch Project Builds
description: Fetch the latest builds of Minecraft projects.

inputs:
  project:
    description: "The project to fetch. One of: paper, velocity, fabric."
  version:
    description: The version to fetch.
outputs:
  build:
    description: The latest build id.
  download-url:
    description: The download url of the latest build.

runs:
  using: 'node16'
  main: 'dist/index.js'
