FROM eclipse-temurin:17-jre-alpine

ARG VELOCITY_DOWNLOAD_URL

RUN apk add wget

RUN addgroup -S minecraft && adduser -S minecraft -G minecraft
USER minecraft

WORKDIR /opt/minecraft

RUN wget $VELOCITY_DOWNLOAD_URL -O velocity.jar

EXPOSE 25565/tcp

ENTRYPOINT java -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75 -XX:+UseG1GC -XX:G1HeapRegionSize=4M \
  -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15 \
  -jar velocity.jar
