name: Build New Docker Images
on:
  schedule:
    - cron: "0,30 * * * *"
  push:
    branches:
      - main
    paths:
      - "./projects.json"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/get-project-builds
