name: Build Paper Images
on:
  schedule:
    - cron: "0,30 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile]
        version: ["1.20.1"]
    steps:
      - uses: actions/checkout@v3

      - id: fetch-builds
        name: Fetch Paper ${{ matrix.version }} Builds
        uses: ./.github/actions/get-project-builds
        with:
          project: paper
          version: ${{ matrix.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./paper/
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            PAPER_DOWNLOAD_URL=${{ fromJson(steps.fetch-builds.outputs.build).downloadUrl }}
          tags: |
            ghcr.io/voxelshift/paper:${{ matrix.version }}
            ghcr.io/voxelshift/paper:${{ matrix.version }}-${{ fromJson(steps.fetch-builds.outputs.build).build }}
