name: Build Velocity Images
on:
  schedule:
    - cron: "0,30 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [debian, alpine]
        version: ["3.2.0-SNAPSHOT"]
    steps:
      - uses: actions/checkout@v3

      - id: fetch-builds
        name: Fetch Velocity ${{ matrix.version }} Builds
        uses: ./.github/actions/get-project-builds
        with:
          project: velocity
          version: ${{ matrix.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          dockerfile: ./velocity/Dockerfile${{ matrix.distribution != 'debian' && format('.{0}', matrix.distribution) || '' }}
          tag-suffix: ${{ matrix.distribution != 'debian' && format('-{0}', matrix.distribution) || '' }}
          # Eclipse Termurin doesn't provide images for arm64 alpine: https://github.com/adoptium/containers/issues/158
          platforms: linux/amd64${{ matrix.distribution == 'debian' && ',linux/arm64' || '' }}
        with:
          context: ./velocity/
          file: ${{ env.dockerfile }}
          platforms: ${{ env.platforms }}
          push: true
          build-args: |
            VELOCITY_DOWNLOAD_URL=${{ steps.fetch-builds.outputs.download-url }}
          tags: |
            ghcr.io/voxelshift/velocity:${{ matrix.version }}${{ env.tag-suffix }}
            ghcr.io/voxelshift/velocity:${{ matrix.version }}-${{ steps.fetch-builds.outputs.build }}${{ env.tag-suffix }}
